### ISSUE TITLE
Should we limit this to just the shell script and associated files

### ISSUE THREAD

**Issue by asuweb** [mailwatch/mailwatch-install-script#1]
Rather than trying to keep the mailwatch branches in sync, would it be an idea to limit the files in this repo to only those needed for the install script.  

The actual mailwatch download could also be handled by the script, either by downloading the zip from github or cloning the repo and checking out the master branch

**Comment by endelwar** [comment]
I think that the installer should be responsible of downloading the lasted **tested** version of MailWatch, by downloading the zip from github instead of using git to clone the repository, I don't know how many sysadmin want to have git installed on the system, while wget or curl are always present.

I personally hate also installer that are piped into shell like `wget -O - http://example.com/install.sh | sudo sh`.

**Comment by asuweb** [comment]
Yes, I agree with you on that

**Comment by stefaweb** [comment]
wget or curl are not installed by default on Debian. Check if exist before.

**Comment by asuweb** [comment]
Yes, on some images they are installed on other they're not.  

The install script installs wget if it's not found

**Comment by endelwar** [comment]
> wget or curl are not installed by default on Debian. Check if exist before.

they are installed by mailscanner install.sh

**Comment by Skywalker-11** [comment]
wget already get installed by the script. 
I created a branch that downloads Mailwatch sources seperately by using git. I though that it is useful for getting the current released version without the need of changing the install script but I'm not sure if that is useful or sshould we fust use wget to get the source?

**Comment by asuweb** [comment]
@Skywalker-11 - use wget to get the latest master branch, that way we're not adding further dependancies
