### ISSUE TITLE
MailScanner Breaking Changes 5.2.1-1 Nov 3 2019

### ISSUE THREAD

**Issue by ghost** [mailwatch/mailwatch-install-script#64]
MailScanner installation method has been refactored and may affect this installation script.

https://github.com/MailScanner/v5

**Comment by ghost** [comment]
I will update the script at the next opportunity.

**Comment by ghost** [comment]
Fixed in commits 8b951b1cd408516a9fb158237632a7f415864cdb and 0fd6c1cb4b0a07eed5edfbcf1ae109ffcf38dd9c

**Comment by Skywalker-11** [comment]
@shawniverson is it intended that the debian package in the MailScanner repo is named
`MailScanner-5.2.1-1-noarch.deb` instead of 
`MailScanner-5.2.1-1.noarch.deb` (`-` instead of `.` after the version)
The other packages do have a `.` there and it is also used the mailwatch-mailscanner.inc that you updated

**Comment by ghost** [comment]
@Skywalker-11 Not intentional.  It appears it was that way in the old package format as well inside the old tarballs.  I'll take a look at the deb packaging and see about changing it to a . instead for consistency.
